name: Java CI

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Build artifact
        run: |
          chmod +x gradlew
          ./gradlew jar
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: glTFrenzy.jar (zipped)
          path: build/libs/glTFrenzy.jar
